# Generated by Django 4.1 on 2022-11-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
    ]
