# Generated by Django 4.1 on 2022-12-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='tags',
        ),
    ]
